title: Mi segundo Blog
theme: minima
author: José Sandoval
email: sandoval2993@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Mi nombre es Jose Miguel Sandoval Tasayco.
# social links
twitter_username: sandoval2993 # DO NOT include the @ character, or else the build will fail!
github_username:  sandoval2993 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
