title: Mi segundo Blog
theme: minima
author: José Sandoval
email: sandoval2993@gmail.com
description: Mi nombre es José Miguel Sandoval Tasayco, Contador titulado de la Universidad Nacional Mayor de San Marcos. |Actualmente me encuentro complementando tanto los conocimientos adquiridos en mi carrera y en mi experiencia laboral con los del mundo de la programación, |para plasmar mis ideas en soluciones empresariales de gran impacto.

twitter_username: sandoval2993 # DO NOT include the @ character, or else the build will fail!
github_username:  sandoval2993 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
